name: Send Daily Discord Message

on:
  schedule:
    # بيشتغل أوتوماتيك كل يوم الساعة 7 الصبح بتوقيت مصر
    - cron: '0 4 * * *'
  workflow_dispatch: # زرار التشغيل اليدوي من تبويب Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python bot.py
